### ISSUE TITLE
[sug] private version for scrims

### ISSUE THREAD

**Issue by Crnsxx** [CardinalDevelopment/Cardinal#4]
Hello kevin or someone else that read this,
is it possible to make an private version with an .JSON file insteed of XML ?

**Comment by twizmwazin** [comment]
Why would this be a useful feature, what is wrong with XML configuration?

**Comment by Pablete1234** [comment]
@twizmwazin we could abstract parsing so that it could have different parsers, but seems like an useless feature to me, plus xml has a quite different structure than json, so making features match would take a while

**Comment by twizmwazin** [comment]
As I'm not interested in making proprietary versions of cardinal nor am I interested in using json, I'm closing this.
