### ISSUE TITLE
[Help] version of sportbukkit

### ISSUE THREAD

**Issue by Crnsxx** [CardinalDevelopment/Cardinal#5]
im getting Error onEnable
http://pastie.org/10911955

**Comment by ElliottWhyman** [comment]
https://github.com/CardinalDevelopment/Cardinal/blob/master/README.md

>Cardinal2 is currently in early development. If you are looking to run Cardinal on your server, please continue using Cardinal1.

Use [CardinalPGM](https://github.com/twizmwazin/CardinalPGM)

**Comment by twizmwazin** [comment]
Your issue is because you aren't using a shaded jar. But, as Elliott said, please continue using cardinal 1.
